(function randomMovie(){

  document.getElementById('btnSorteio').addEventListener('click', function(){
    var movieList = [
    "2001 Uma Odisséia no espaço",
    "Laranja Mecânica",
    "Por um punhado de dólares",
    "Depois de Lúcia",
    "Amadeus",
    "O Fabuloso Destino de Amélie Poulain",
    "Argo",
    "Tempo de Despertar",
    "Beasts of No Nation",
    "Birdman",
    "Biutiful",
    "Aliança do Crime",
    "Cisne Negro #netflix",
    "Blade Runner",
    "Ponte dos espiões",
    "Brooklyn",
    "Carol",
    "Filhos da Esperança",
    "Um Conto Chinês",
    "Um Homem Entre Gigantes",
    "Creed: Nascido para Lutar",
    "Horizonte Profundo - Desastre no Golfo",
    "Um Ato de Liberdade",
    "Brilho Eterno de uma Mente sem lembranças",
    "Evereste",
    "Ex-Machina",
    "O Voo - #netflix",
    "Florence: Quem é essa mulher",
    "Por uns Dólares a Mais",
    "Corações de Ferro",
    "Gattaca: Experiência Galáctica",
    "Godzilla",
    "GoodFellas",
    "Os Bons Companheiros",
    "Até o Último Homem",
    "Fogo Contra Fogo",
    "A Qualquer Custo",
    "Estrelas além do Tempo",
    "Indie Game - The Movie",
    "Interestelar",
    "Invictus",
    "O Grande Mestre #netflix",
    "Kill Bill - Volume 1",
    "La La Land",
    "Lady Vingança",
    "Terra de Minas",
    "Cartas de Iwo Jima",
    "Lion",
    "Pequena Miss Sunchine",
    "Jogos, Trapaças e Dois Canos Fumegantes - #netflix",
    "O Senhor das Armas",
    "O Profissional",
    "Chamas da Vingança",
    "Manchester à Beira-Mar",
    "Maradona By Kusturica #netflix",
    "O Expresso da Meia-Noite",
    "Armas na Mesa",
    "Mississipi em Chamas",
    "Moneyball",
    "Mr Nobody",
    "Munique",
    "Nebraska",
    "Animais Noturnos",
    "O.J Made in America",
    "Era uma Vez no Oeste",
    "Um Estranho no Ninho #netflix",
    "Círculo de Fogo",
    "Particle Fever",
    "Piratas da Informática",
    "O Predestinado",
    "Os Suspeitos",
    "Prometheus",
    "Psicose",
    "Pulp Fiction",
    "Touro Indomável",
    "Rain Man",
    "Requiem for the American Dream - #netflix",
    "Se7en",
    "Senna #netflix",
    "Sicário #netflix",
    "Silence",
    "Sin City",
    "Expresso do Amanhã",
    "Nocaute",
    "As Sufragistas",
    "Mr. Vingança",
    "T2 Trainspotting",
    "Taxi Driver",
    "Team Foxcatcher",
    "O Espetacular Homem Aranha",
    "A Grande Aposta",
    "A Garota Dinamarquesa",
    "A hora da Zona Morta",
    "O Poderoso Chefão",
    "O Poderoso Chefão II",
    "Três Homens em Conflito",
    "Os Oito Odiados - #netflix",
    "Guerra ao Terror",
    "Conexão Escobar",
    "Perdido em Marte",
    "O Mestre",
    "O Lugar onde Tudo Termina",
    "A Tartatura Vermelha",
    "O Regresso",
    "Ring: O Chamado",
    "O Apartamento",
    "Um sonho de Liberdade",
    "O Iluminado",
    "O Silêncio dos Inocentes",
    "A Informante",
    "O Lobo de Wall Street",
    "O Sol é Para Todos - #netflix",
    "Toni Erdmann",
    "Invencível - #netflix",
    "V de Vingança",
    "Um corpo que Cai",
    "Johny & June",
    "Cavalo de Guerra",
    "Watchmen - #netflix",
    "Guerra Mundial Z",
    "Zodíaco - #netflix",
    "Jackie",
    "O Senhor das Moscas"
  ];

  var randomMovie = Math.floor(Math.random() * movieList.length) + 1;
    
  document.getElementById('nomeFilme').innerHTML = (movieList[randomMovie]);
    
  console.log(movieList.length);

  });

})();